--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jojoe77777/FormAPI
branches:
  - master
projects:
  LibHackBlockAndItemRegistry:
    path: ""
    type: library
    model: virion
...
