--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AID-LEARNING/LibHackBlockAndItemRegistry
branches:
  - master
projects:
  LibHackBlockAndItemRegistry:
    path: ""
    type: library
    model: virion
...
